#makefile

# $@ .... name of target
# $^ ... list of dependencies

SHELL = /bin/bash 
#CFLAGS = -fpic -g

lib: /home/ernsts/BIEN4290/Lab1
g++ ernsts_corr.cpp ernsts_stats.cpp -o [exe name] -l [lib name w/o .so]


clean: 
	rm -f *.o
	rm -f *.gch
