CC = g++

seememow.o: mowin.cpp seememow.cpp thehob.cpp tthti.cpp
 	g++ -c $^

tthti.o: mowin.cpp seememow.cpp thehob.cpp tthti.cpp
 	g++ -c $^

tthti: mowin.cpp seememow.cpp thehob.cpp tthti.cpp
 	g++ -o /home/ernsts/BIEN4290/Midterm/midterm2022/MoarComplicated/


clean:
 	 rm -f *.o
 	 rm -f *.gch
